/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8fafb",
        "surface-container": "#eceeef",
        "surface-container-highest": "#e1e3e4",
        "surface-container-high": "#e6e8e9",
        "surface-container-low": "#f2f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#436182",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "inverse-primary": "#abc9ef",
        "outline": "#73777e",
        "outline-variant": "#c3c6ce",
        "background": "#f8fafb",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-surface-variant": "#43474d",
        "primary": "#002542",
        "on-primary": "#ffffff",
        "primary-container": "#1b3b5a",
        "on-primary-container": "#87a5ca",
        "primary-fixed": "#d1e4ff",
        "primary-fixed-dim": "#abc9ef",
        "on-primary-fixed": "#001d35",
        "on-primary-fixed-variant": "#2a4968",
        "secondary": "#4c616c",
        "on-secondary": "#ffffff",
        "secondary-container": "#cfe6f2",
        "on-secondary-container": "#526772",
        "secondary-fixed": "#cfe6f2",
        "secondary-fixed-dim": "#b4cad6",
        "on-secondary-fixed": "#071e27",
        "on-secondary-fixed-variant": "#354a53",
        "tertiary": "#322000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e3400",
        "on-tertiary-container": "#d79600",
        "tertiary-fixed": "#ffdeac",
        "tertiary-fixed-dim": "#ffba38",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-fixed-variant": "#604100",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
